spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:customers
    password: '{cipher}593920fcf69793a265899cfdf55a9c13d79775901b01c1676675eab52192fc6d'
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  application:
    name: Customers



#server:
#  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka